name: Pebble

on:
  push:
    branches: ['main', '*-ci']
  pull_request:
  schedule:
    - cron: "25 6 * * 5"

jobs:
  pebble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Clone Pebble repo
        uses: actions/checkout@v4
        with:
          repository: letsencrypt/pebble
          path: pebble-src
      - name: Build Pebble binaries
        working-directory: pebble-src
        run: |
          go build -o $GITHUB_WORKSPACE/pebble ./cmd/pebble
          go build -o $GITHUB_WORKSPACE/pebble-challtestsrv ./cmd/pebble-challtestsrv
      - name: Run integration test
        run: RUST_LOG=pebble=info cargo test --features=x509-parser --features=time -- --ignored
