name: Pebble

on:
  push:
    branches: ['main', '*-ci']
  pull_request:
  schedule:
    - cron: "25 6 * * 5"

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Download Pebble
        run: |
          curl -L "https://github.com/letsencrypt/pebble/releases/latest/download/pebble-linux-amd64.tar.gz" | tar xz --strip-components=3
          chmod +x pebble
      - name: Download Pebble Challenge Test Server
        run: |
          curl -L "https://github.com/letsencrypt/pebble/releases/latest/download/pebble-challtestsrv-linux-amd64.tar.gz" | tar xz --strip-components=3
          chmod +x pebble-challtestsrv
      - name: Run integration test
        run: RUST_LOG=integration=info cargo test --test integration
